import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {Controller} from '../core.mjs';import {livekitJWT} from '../adapters.mjs';import {serverFor} from '../server.mjs';
async function fixture(){let now=0;const allowed=new Set();let failRevoke=false;const c=new Controller({devices:{pixel:'p'.repeat(32),iphone:'i'.repeat(32)},clock:()=>now,media:{token:async()=>({token:'synthetic',url:'wss://example.invalid'}),remove:async id=>allowed.delete(id),permission:async(id,yes)=>{if(!yes&&failRevoke)throw Error('network');yes?allowed.add(id):allowed.delete(id);assert.ok(allowed.size<=1);}}});let p=(await c.login('pixel','p'.repeat(32))).session;let i=(await c.login('iphone','i'.repeat(32))).session;return {c,p,i,allowed,advance:ms=>now+=ms,fail:()=>failRevoke=true,restore:()=>failRevoke=false};}
test('simultaneous requests have one winner',async()=>{const f=await fixture();const r=await Promise.all([f.c.request(f.p,randomUUID()),f.c.request(f.i,randomUUID())]);assert.equal(r.filter(x=>x.granted).length,1);assert.equal(f.allowed.size,1);});
test('stale epochs cannot release or renew',async()=>{const f=await fixture(),a=await f.c.request(f.p,randomUUID());await assert.rejects(f.c.renew(f.p,a.epoch+1));await assert.rejects(f.c.release(f.i,a.epoch));assert.equal(f.allowed.size,1);});
test('expiry revokes before granting another device',async()=>{const f=await fixture();await f.c.request(f.p,randomUUID());f.advance(4001);assert.equal((await f.c.request(f.i,randomUUID())).granted,true);assert.equal(f.allowed.size,1);});
test('release revokes; repeated press identity rejected',async()=>{const f=await fixture(),id=randomUUID(),a=await f.c.request(f.p,id);await f.c.release(f.p,a.epoch);assert.equal(f.allowed.size,0);await assert.rejects(f.c.request(f.p,id));});
test('failed revocation blocks new owner',async()=>{const f=await fixture();await f.c.request(f.p,randomUUID());f.advance(4001);f.fail();await assert.rejects(f.c.request(f.i,randomUUID()));assert.equal(f.allowed.size,1);f.restore();await f.c.tick();assert.equal(f.allowed.size,0);});
test('renewable lease has no maximum turn cap',async()=>{const f=await fixture(),a=await f.c.request(f.p,randomUUID());for(let n=0;n<100;n++){f.advance(3000);await f.c.renew(f.p,a.epoch);}assert.equal(f.allowed.size,1);});
test('replacement session revokes and invalidates previous session',async()=>{const f=await fixture();await f.c.request(f.p,randomUUID());await f.c.login('pixel','p'.repeat(32));await assert.rejects(f.c.status(f.p));assert.equal(f.allowed.size,0);});
test('wrong pairing credentials and absent session rejected',async()=>{const f=await fixture();await assert.rejects(f.c.login('pixel','bad'));await assert.rejects(f.c.login('unknown','p'.repeat(32)));await assert.rejects(f.c.request('bad',randomUUID()));});
test('only authorized iPhone session may register APNs token',async()=>{const f=await fixture();await assert.rejects(f.c.push(f.p,'ab'.repeat(32)));await f.c.push(f.i,'ab'.repeat(32));});
test('HTTP boundaries reject unauthorized calls and oversized data',async()=>{const f=await fixture(),server=serverFor(f.c);await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const url='http://127.0.0.1:'+server.address().port;const a=await fetch(url+'/request',{method:'POST',body:'{}'});assert.equal(a.status,401);const b=await fetch(url+'/login',{method:'POST',body:'x'.repeat(4097)});assert.equal(b.status,413);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}});
test('receive token never grants publish/admin and expires',()=>{const token=livekitJWT('test','synthetic','receiver',{roomJoin:true,room:'slime-talk-feasibility',canSubscribe:true,canPublish:false,canPublishData:false});const claims=JSON.parse(Buffer.from(token.split('.')[1],'base64url'));assert.equal(claims.video.canPublish,false);assert.equal(claims.video.roomAdmin,undefined);assert.equal(claims.exp-claims.iat,60);});
